name: Change Background

on:
  workflow_dispatch:  # Trigger manual untuk menjalankan workflow

jobs:
  change-background:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests

      - name: Change Background
        run: python .github/scripts/change_background.py

    env:
      STORE_ID: ${{ secrets.STORE_ID }}
      DEVICE_ID: ${{ secrets.DEVICE_ID }}
      OCP_APIM_SUBSCRIPTION_KEY: ${{ secrets.OCP_APIM_SUBSCRIPTION_KEY }}
      FILE_URL: ${{ vars.FILE_URL }}  # Mengambil URL dari GitHub Actions Variable
